build:	
	g++ main.cpp grapher/graph.cpp geometry/Polygon.cpp geometry/Point.cpp convexHull/gift_wrapping.cpp convexHull/pointExclussion.cpp cli/handlers/handlers.cpp cli/handlers/utils.cpp \
	-o example_plot \
	-I /usr/include/python3.10/ -lpython3.10

run:
	./example_plot